variables:
  DOCKER_DRIVER: overlay2
  KERNEL: 'bzImage'
  ROOTFS_NAME: 'ubuntu-19.04-desktopV4-amd64.img.qcow2'
  ROOTFS_IMAGE_URL: 'https://people.collabora.com/~laks/lava/kernel_test/ubuntu-19.04-desktopV4-amd64.img.qcow2.gz'
  
before_script:
   - apt-get update -y

stages:
  - build
  - notify

kernel build:
  stage: build
  tags:
     - autoscaled 
  before_script:
    - apt-get update -y
    - apt-get install -y rsync git build-essential bc kmod cpio flex cpio libncurses5-dev bison libssl-dev libelf-dev openssh-client curl qemu-system*
  script:
     - make x86_64_defconfig && make kvmconfig 
     - echo -e "CONFIG_FUTEX2=y\nCONFIG_SYSCALL_USER_DISPATCH=y\nCONFIG_SND_SOC_CS35L41=y\nCONFIG_SND_SOC_CS35L41_SPI=y\nCONFIG_SND_SOC_CS35L41_I2C=y\nCONFIG_DRM_AMDGPU=y\nCONFIG_DRM_AMDGPU_SI=y\nCONFIG_DRM_AMDGPU_CIK=y\nCONFIG_DRM_AMDGPU_USERPTR=y\nCONFIG_DRM_AMDGPU_GART_DEBUGFS=y" >> .config
     - make -j`nproc`
     - git rev-parse HEAD &> commit_id_file
     - cp -v arch/x86/boot/bzImage .
     # download rootfs
     - curl  ${ROOTFS_IMAGE_URL} -o "${ROOTFS_NAME}.gz"
     - gunzip "${ROOTFS_NAME}.gz"
     - echo "Running cmd $QEMU_CMD"
     - qemu-system-x86_64 -enable-kvm -nographic -kernel ${KERNEL} -drive file=${ROOTFS_NAME},format=qcow2 -device virtio-serial-pci -virtfs local,path=$(pwd),mount_tag=steamlogs,security_model=none -m 2G -smp 2 -cpu host -net user,hostfwd=tcp::2222-:22 -net nic,model=virtio --append "root=/dev/sda1 rw console=ttyS0"    
     # notify
     - test -f "fail.txt" && exit 1
     - echo "All tests passed"

  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - bzImage
      - kernel_results.log
